-- ===========================================================================
--  Xetral — Phase 6: Bills, eSIM and virtual numbers
--  packages/ledger/sql/004_purchases.sql
--
--  One table for every "buy a thing from a provider" — airtime, data, an
--  electricity token, an eSIM, a phone number. The providers differ; the money
--  question does not.
-- ===========================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- WHY A PURCHASE IS TWO LEDGER ENTRIES, NOT ONE
--
-- The customer's money must be committed BEFORE we ask a provider for
-- anything, or we are buying on credit we never agreed to extend. But the
-- purchase can still fail, and money taken for something never delivered has
-- to come back.
--
--   Reserve   wallet  -> pending            the overdraft guard decides here
--   Settle    pending -> provider_float     the purchase really happened
--   Reverse   pending -> wallet             a reversal, appended not edited
--
-- This is the same shape as a card authorization, and for the same reason: the
-- moment money is committed and the moment it is spent are different moments,
-- and a ledger that cannot express the gap has to lie about one of them.
--
-- A purchase left in `reserved` is not stuck — it is money correctly held
-- while we find out what happened. `pending_purchases` below is the queue a
-- reconciliation job reads.
-- ---------------------------------------------------------------------------

CREATE TYPE purchase_status AS ENUM ('reserved', 'delivered', 'failed', 'reversed');

CREATE TABLE purchases (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid               UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id            BIGINT          NOT NULL REFERENCES users(id),

    -- OUR reference, and the root of both ledger idempotency keys. It is what
    -- the provider is told to call this purchase, so it is generated by us and
    -- is not the customer's key: two customers WILL eventually send the same
    -- key — a client counting from one is enough — and a globally unique column
    -- fed straight from customer input turns that into one of them failing
    -- with money already reserved.
    reference          TEXT            NOT NULL,

    -- The customer's key, unique PER CUSTOMER. This is what a retry is matched
    -- on, and scoping it to the user is what makes "the same purchase" a
    -- question about one customer rather than about the whole table.
    idempotency_key    TEXT            NOT NULL,

    provider           TEXT            NOT NULL,
    service            TEXT            NOT NULL
                       CHECK (service IN ('airtime', 'data', 'utility', 'esim', 'number')),
    item_code          TEXT            NOT NULL,

    -- The phone or meter number the customer typed. Not a secret, but it is
    -- personal data, so nothing here invites logging the whole row.
    target             TEXT            NOT NULL,

    amount_minor       BIGINT          NOT NULL CHECK (amount_minor > 0),
    currency           TEXT            NOT NULL,

    status             purchase_status NOT NULL DEFAULT 'reserved',
    provider_reference TEXT            NULL,

    -- Sealed with a key-versioned envelope, not stored in the clear. An
    -- electricity token is a bearer instrument: whoever holds it before it is
    -- used can spend it, so a database dump containing one is a dump of live
    -- money. The CHECK makes the sealing structural rather than customary.
    delivery_sealed    TEXT            NULL CHECK (delivery_sealed IS NULL
                                                   OR delivery_sealed ~ '^v[0-9]+:'),

    -- The entry a reversal would point at. Kept so the reversal can name it
    -- without re-deriving it from an idempotency key.
    reserve_entry_id   BIGINT          NULL REFERENCES journal_entries(id),
    failure_reason     TEXT            NULL,

    created_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),

    CONSTRAINT purchases_uuid_key      UNIQUE (uuid),
    CONSTRAINT purchases_reference_key UNIQUE (reference),
    CONSTRAINT purchases_user_key      UNIQUE (user_id, idempotency_key),

    -- A delivered purchase must say what the provider called it. Without that
    -- there is nothing to reconcile against, and "delivered" is just a claim.
    CONSTRAINT delivered_has_reference CHECK (
        status <> 'delivered' OR provider_reference IS NOT NULL
    ),
    CONSTRAINT failed_has_reason CHECK (
        status <> 'failed' OR failure_reason IS NOT NULL
    )
);

CREATE INDEX purchases_user    ON purchases (user_id, created_at DESC);
CREATE INDEX purchases_pending ON purchases (created_at) WHERE status = 'reserved';

-- A finished purchase stays finished. Reopening one would let a delivered
-- token be re-delivered, or a reversed charge be silently re-applied.
CREATE OR REPLACE FUNCTION assert_purchase_outcome_final() RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status <> 'reserved' AND NEW.status IS DISTINCT FROM OLD.status THEN
        RAISE EXCEPTION 'purchase % is already %; an outcome is final',
            OLD.id, OLD.status
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.reference IS DISTINCT FROM OLD.reference
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.user_id IS DISTINCT FROM OLD.user_id
       OR NEW.amount_minor IS DISTINCT FROM OLD.amount_minor THEN
        RAISE EXCEPTION 'purchase % identity and amount are immutable', OLD.id
            USING ERRCODE = 'check_violation';
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER purchases_outcome_final
    BEFORE UPDATE ON purchases
    FOR EACH ROW EXECUTE FUNCTION assert_purchase_outcome_final();

-- The reconciliation queue. Every row here is a customer's money held against
-- a purchase whose outcome we do not yet know, and the oldest ones are the
-- ones worth asking a provider about.
CREATE OR REPLACE VIEW pending_purchases AS
SELECT p.id AS purchase_id,
       p.uuid AS purchase_uuid,
       p.user_id,
       p.provider,
       p.service,
       p.reference,
       p.amount_minor,
       p.currency,
       p.created_at,
       now() - p.created_at AS held_for
  FROM purchases p
 WHERE p.status = 'reserved'
 ORDER BY p.created_at;

COMMIT;
